# Generated by Django 3.2.8 on 2021-11-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginscreen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
