# Generated by Django 3.2.8 on 2021-11-02 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginscreen', '0002_destination_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='age',
            new_name='location',
        ),
    ]
