# Generated by Django 3.2.8 on 2021-11-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginscreen', '0003_rename_age_destination_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='location',
            new_name='bot_number',
        ),
        migrations.AddField(
            model_name='destination',
            name='date',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='greenhouse',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='location_xyz',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='time',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
