# Generated by Django 3.2.8 on 2021-11-04 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loginscreen', '0004_auto_20211103_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='name',
            new_name='plant_name',
        ),
        migrations.AddField(
            model_name='destination',
            name='authuser',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userinfo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='destination',
            name='user_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
