# Generated by Django 3.2.8 on 2021-11-04 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginscreen', '0005_auto_20211104_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='authuser',
        ),
    ]
