# Generated by Django 3.2.8 on 2021-11-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginscreen', '0006_remove_destination_authuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='location_xyz',
        ),
        migrations.AddField(
            model_name='destination',
            name='location_x',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='location_y',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='location_z',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
