# Generated by Django 3.2.8 on 2021-11-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginscreen', '0007_auto_20211122_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='greenhouse',
        ),
        migrations.AddField(
            model_name='destination',
            name='bot_run',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='plant_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
