# Generated by Django 3.2.8 on 2021-11-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginscreen', '0008_auto_20211122_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='plant_height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
