# Generated by Django 3.2.8 on 2021-11-23 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginscreen', '0009_destination_plant_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='plant_height',
        ),
    ]
