# Generated by Django 3.2.8 on 2021-11-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginscreen', '0010_remove_destination_plant_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='accuracy',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
